vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
     # alias qui nous permet d'accéder à nos images depuis le navigateur
        photo_file:
            uri_prefix: /uploads/images/photo
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
