controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# download cv
download_cv:
    path: /../public/downloads
    controller: App\Controller\CVController::index
